version: "2"
services:
  spark:
    image: jupyter/sparkmagic-livy
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark
    ports:
      - "8998:8998"
      - "11000:11000"
    environment:
      - YARN_CONF_DIR=/etc/hadoop
  jupyter:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "false"
    links:
      - spark
    ports:
      - "8888:8888"
